let a = 6;
let b = 3;
console.log("a:",a,"b:",b);
console.log("Arithmetic Operations:");
console.log("Addition Operator: ",a+b);
console.log("subtraction Operator: ",a-b);
console.log("Multiplication Operator: ",a*b);
console.log("divison Operator: ",a/b);
console.log("Modulus Operator: ",a%b);
console.log("Power Operator: ",a**b);
console.log("\n");
console.log("Assignment Operations: ");
console.log(" Addition Assignment Operator: ",a+=b);
console.log(" Subtraction Assignment Operator: ",a-=b);
console.log(" Multiplication Assignment Operator: ",a*=b);
console.log(" Divsion Assignment Operator: ",a/=b);
console.log(" Modulus Assignment Operator: ",a%=b);
console.log("\n");
console.log("Comparsion Operations: ");
console.log(" Lessthan Operator: ",a<b);
console.log(" Greaterthan Operator: ",a>b);
console.log(" Lessthan or equalto Operator: ",a<=b);
console.log("  Greaterthan or equalto Operator: ",a>=b);
console.log(" Equal to Operator: ",a==b);
console.log(" Not Equal to Operator: ",a!=b);
console.log(" Value and data type are equal Operator: ",a===b);
console.log(" Value and data type are not equal Operator: ",a!==b);
console.log("\n");
console.log("Logical Operations: ");
console.log(" if the both conditions are true than it will return True: ",a<b && a>b);
console.log(" if the both conditions are false than it will return False: ",a<b || a>b);
console.log(" it will return the opposite value or the satisfying condition: ",!(a>b));
console.log("\n");
console.log("Bitwise Operations: ");
console.log(" Bitwise And: ",(a&b));
console.log(" Bitwise OR: ",(a|b));
console.log(" Bitwise  XOR: ",(a^b));
console.log(" Bitwise NOT: ",(~a));
console.log(" Liftshift: ",(a<<1));
console.log(" Rightshift : ",(a>>1));
console.log("\n");
console.log(" Ternary Operator: ");
let el =18;
let ell = (el>=18) ? "Eligible to Vote" : "Note";
console.log(ell);
console.log(typeof a);
console.log(typeof ell);
